// Generated automatically by nearley, version 2.19.0
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

 const g = require("./code.js");
 const lexer = g.lexer;
var grammar = {
    Lexer: lexer,
    ParserRules: [
    {"name": "Date", "symbols": [(lexer.has("number") ? {type: "number"} : number)]},
    {"name": "TimeQ$ebnf$1$subexpression$1", "symbols": [{"literal":"o'clock"}, (lexer.has("space") ? {type: "space"} : space)]},
    {"name": "TimeQ$ebnf$1", "symbols": ["TimeQ$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "TimeQ$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "TimeQ$subexpression$1", "symbols": [{"literal":"AM"}]},
    {"name": "TimeQ$subexpression$1", "symbols": [{"literal":"am"}]},
    {"name": "TimeQ$subexpression$1", "symbols": [{"literal":"PM"}]},
    {"name": "TimeQ$subexpression$1", "symbols": [{"literal":"pm"}]},
    {"name": "TimeQ", "symbols": ["TimeQ$ebnf$1", "TimeQ$subexpression$1"], "postprocess": g.timeQ},
    {"name": "Time0$ebnf$1$subexpression$1$subexpression$1$subexpression$1$ebnf$1", "symbols": [(lexer.has("space") ? {type: "space"} : space)], "postprocess": id},
    {"name": "Time0$ebnf$1$subexpression$1$subexpression$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time0$ebnf$1$subexpression$1$subexpression$1$subexpression$1$subexpression$1", "symbols": [{"literal":":"}]},
    {"name": "Time0$ebnf$1$subexpression$1$subexpression$1$subexpression$1$subexpression$1", "symbols": [{"literal":"."}]},
    {"name": "Time0$ebnf$1$subexpression$1$subexpression$1$subexpression$1$subexpression$1", "symbols": [{"literal":"-"}]},
    {"name": "Time0$ebnf$1$subexpression$1$subexpression$1$subexpression$1$subexpression$1", "symbols": [{"literal":"and"}]},
    {"name": "Time0$ebnf$1$subexpression$1$subexpression$1$subexpression$1$ebnf$2", "symbols": [(lexer.has("space") ? {type: "space"} : space)], "postprocess": id},
    {"name": "Time0$ebnf$1$subexpression$1$subexpression$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time0$ebnf$1$subexpression$1$subexpression$1$subexpression$1", "symbols": ["Time0$ebnf$1$subexpression$1$subexpression$1$subexpression$1$ebnf$1", "Time0$ebnf$1$subexpression$1$subexpression$1$subexpression$1$subexpression$1", "Time0$ebnf$1$subexpression$1$subexpression$1$subexpression$1$ebnf$2"]},
    {"name": "Time0$ebnf$1$subexpression$1$subexpression$1", "symbols": ["Time0$ebnf$1$subexpression$1$subexpression$1$subexpression$1"]},
    {"name": "Time0$ebnf$1$subexpression$1$subexpression$1", "symbols": [(lexer.has("space") ? {type: "space"} : space)]},
    {"name": "Time0$ebnf$1$subexpression$1", "symbols": ["Time0$ebnf$1$subexpression$1$subexpression$1", (lexer.has("number") ? {type: "number"} : number)]},
    {"name": "Time0$ebnf$1", "symbols": ["Time0$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Time0$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time0$ebnf$2$subexpression$1", "symbols": [(lexer.has("space") ? {type: "space"} : space), "TimeQ"]},
    {"name": "Time0$ebnf$2", "symbols": ["Time0$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "Time0$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Time0", "symbols": [(lexer.has("number") ? {type: "number"} : number), "Time0$ebnf$1", "Time0$ebnf$2"], "postprocess": g.time0},
    {"name": "Time", "symbols": [{"literal":"at"}, (lexer.has("space") ? {type: "space"} : space), "Time0"], "postprocess": g.time},
    {"name": "RelativeDay$subexpression$1", "symbols": [{"literal":"today"}]},
    {"name": "RelativeDay$subexpression$1", "symbols": [{"literal":"tommorow"}]},
    {"name": "RelativeDay$subexpression$1", "symbols": [{"literal":"yesterday"}]},
    {"name": "RelativeDay", "symbols": ["RelativeDay$subexpression$1"], "postprocess": function ([[x]]) {return x;}},
    {"name": "DayOfWeek$subexpression$1", "symbols": [{"literal":"Sunday"}]},
    {"name": "DayOfWeek$subexpression$1", "symbols": [{"literal":"Monday"}]},
    {"name": "DayOfWeek$subexpression$1", "symbols": [{"literal":"Tuesday"}]},
    {"name": "DayOfWeek$subexpression$1", "symbols": [{"literal":"Wednesday"}]},
    {"name": "DayOfWeek$subexpression$1", "symbols": [{"literal":"Thursday"}]},
    {"name": "DayOfWeek$subexpression$1", "symbols": [{"literal":"Friday"}]},
    {"name": "DayOfWeek$subexpression$1", "symbols": [{"literal":"Saturday"}]},
    {"name": "DayOfWeek", "symbols": ["DayOfWeek$subexpression$1"], "postprocess": function ([[x],]){ return g.weekday.findIndex(e => x == e);}},
    {"name": "DayOfWeek$subexpression$2", "symbols": [{"literal":"Sun"}]},
    {"name": "DayOfWeek$subexpression$2", "symbols": [{"literal":"Mon"}]},
    {"name": "DayOfWeek$subexpression$2", "symbols": [{"literal":"Tue"}]},
    {"name": "DayOfWeek$subexpression$2", "symbols": [{"literal":"Wed"}]},
    {"name": "DayOfWeek$subexpression$2", "symbols": [{"literal":"Thu"}]},
    {"name": "DayOfWeek$subexpression$2", "symbols": [{"literal":"Fri"}]},
    {"name": "DayOfWeek$subexpression$2", "symbols": [{"literal":"Sat"}]},
    {"name": "DayOfWeek$ebnf$1", "symbols": [(lexer.has("space") ? {type: "space"} : space)], "postprocess": id},
    {"name": "DayOfWeek$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "DayOfWeek", "symbols": ["DayOfWeek$subexpression$2", "DayOfWeek$ebnf$1", {"literal":"."}], "postprocess": function ([[x],...zz]){return g.weekdayshort.findIndex(e => x == e);}},
    {"name": "MonthOfYear$subexpression$1", "symbols": [{"literal":"January"}]},
    {"name": "MonthOfYear$subexpression$1", "symbols": [{"literal":"Febuary"}]},
    {"name": "MonthOfYear$subexpression$1", "symbols": [{"literal":"March"}]},
    {"name": "MonthOfYear$subexpression$1", "symbols": [{"literal":"April"}]},
    {"name": "MonthOfYear$subexpression$1", "symbols": [{"literal":"May"}]},
    {"name": "MonthOfYear$subexpression$1", "symbols": [{"literal":"June"}]},
    {"name": "MonthOfYear$subexpression$1", "symbols": [{"literal":"July"}]},
    {"name": "MonthOfYear$subexpression$1", "symbols": [{"literal":"August"}]},
    {"name": "MonthOfYear$subexpression$1", "symbols": [{"literal":"September"}]},
    {"name": "MonthOfYear$subexpression$1", "symbols": [{"literal":"October"}]},
    {"name": "MonthOfYear$subexpression$1", "symbols": [{"literal":"November"}]},
    {"name": "MonthOfYear$subexpression$1", "symbols": [{"literal":"December"}]},
    {"name": "MonthOfYear", "symbols": ["MonthOfYear$subexpression$1"], "postprocess": function ([[x],,]){return g.monthday.findIndex(e => x == e);}},
    {"name": "MonthOfYear$subexpression$2", "symbols": [{"literal":"Jan"}]},
    {"name": "MonthOfYear$subexpression$2", "symbols": [{"literal":"Feb"}]},
    {"name": "MonthOfYear$subexpression$2", "symbols": [{"literal":"Mar"}]},
    {"name": "MonthOfYear$subexpression$2", "symbols": [{"literal":"Apr"}]},
    {"name": "MonthOfYear$subexpression$2", "symbols": [{"literal":"May"}]},
    {"name": "MonthOfYear$subexpression$2", "symbols": [{"literal":"Jun"}]},
    {"name": "MonthOfYear$subexpression$2", "symbols": [{"literal":"Jul"}]},
    {"name": "MonthOfYear$subexpression$2", "symbols": [{"literal":"Aug"}]},
    {"name": "MonthOfYear$subexpression$2", "symbols": [{"literal":"Sep"}]},
    {"name": "MonthOfYear$subexpression$2", "symbols": [{"literal":"Oct"}]},
    {"name": "MonthOfYear$subexpression$2", "symbols": [{"literal":"Nov"}]},
    {"name": "MonthOfYear$subexpression$2", "symbols": [{"literal":"Dec"}]},
    {"name": "MonthOfYear$ebnf$1", "symbols": [(lexer.has("space") ? {type: "space"} : space)], "postprocess": id},
    {"name": "MonthOfYear$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "MonthOfYear", "symbols": ["MonthOfYear$subexpression$2", "MonthOfYear$ebnf$1", {"literal":"."}], "postprocess": function ([[x],,]){return g.monthdayshort.findIndex(e => x == e);}},
    {"name": "Date0$ebnf$1$subexpression$1", "symbols": [{"literal":"nd"}]},
    {"name": "Date0$ebnf$1$subexpression$1", "symbols": [{"literal":"st"}]},
    {"name": "Date0$ebnf$1$subexpression$1", "symbols": [{"literal":"th"}]},
    {"name": "Date0$ebnf$1", "symbols": ["Date0$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Date0$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Date0$ebnf$2$subexpression$1$ebnf$1$subexpression$1$ebnf$1", "symbols": [(lexer.has("space") ? {type: "space"} : space)], "postprocess": id},
    {"name": "Date0$ebnf$2$subexpression$1$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Date0$ebnf$2$subexpression$1$ebnf$1$subexpression$1$subexpression$1", "symbols": [{"literal":"year"}]},
    {"name": "Date0$ebnf$2$subexpression$1$ebnf$1$subexpression$1$subexpression$1", "symbols": [{"literal":"y"}]},
    {"name": "Date0$ebnf$2$subexpression$1$ebnf$1$subexpression$1", "symbols": ["Date0$ebnf$2$subexpression$1$ebnf$1$subexpression$1$ebnf$1", "Date0$ebnf$2$subexpression$1$ebnf$1$subexpression$1$subexpression$1"]},
    {"name": "Date0$ebnf$2$subexpression$1$ebnf$1", "symbols": ["Date0$ebnf$2$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "Date0$ebnf$2$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Date0$ebnf$2$subexpression$1", "symbols": [(lexer.has("space") ? {type: "space"} : space), (lexer.has("number") ? {type: "number"} : number), "Date0$ebnf$2$subexpression$1$ebnf$1"]},
    {"name": "Date0$ebnf$2", "symbols": ["Date0$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "Date0$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Date0", "symbols": [(lexer.has("number") ? {type: "number"} : number), "Date0$ebnf$1", (lexer.has("space") ? {type: "space"} : space), "MonthOfYear", "Date0$ebnf$2"], "postprocess": g.date04},
    {"name": "Date0$ebnf$3$subexpression$1$subexpression$1", "symbols": [{"literal":"next"}]},
    {"name": "Date0$ebnf$3$subexpression$1$subexpression$1", "symbols": [{"literal":"last"}]},
    {"name": "Date0$ebnf$3$subexpression$1$subexpression$1", "symbols": [{"literal":"this"}]},
    {"name": "Date0$ebnf$3$subexpression$1", "symbols": ["Date0$ebnf$3$subexpression$1$subexpression$1", (lexer.has("space") ? {type: "space"} : space)]},
    {"name": "Date0$ebnf$3", "symbols": ["Date0$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "Date0$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Date0", "symbols": ["Date0$ebnf$3", "DayOfWeek"], "postprocess": g.date03},
    {"name": "Date0$ebnf$4$subexpression$1$subexpression$1", "symbols": [{"literal":"next"}]},
    {"name": "Date0$ebnf$4$subexpression$1$subexpression$1", "symbols": [{"literal":"last"}]},
    {"name": "Date0$ebnf$4$subexpression$1$subexpression$1", "symbols": [{"literal":"this"}]},
    {"name": "Date0$ebnf$4$subexpression$1", "symbols": ["Date0$ebnf$4$subexpression$1$subexpression$1", (lexer.has("space") ? {type: "space"} : space)]},
    {"name": "Date0$ebnf$4", "symbols": ["Date0$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "Date0$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "Date0", "symbols": ["Date0$ebnf$4", "MonthOfYear"], "postprocess": g.date02},
    {"name": "Date0$subexpression$1", "symbols": [{"literal":"next"}]},
    {"name": "Date0$subexpression$1", "symbols": [{"literal":"last"}]},
    {"name": "Date0$subexpression$1", "symbols": [{"literal":"this"}]},
    {"name": "Date0$subexpression$2", "symbols": [{"literal":"week"}]},
    {"name": "Date0$subexpression$2", "symbols": [{"literal":"month"}]},
    {"name": "Date0$subexpression$2", "symbols": [{"literal":"year"}]},
    {"name": "Date0$subexpression$2", "symbols": [{"literal":"day"}]},
    {"name": "Date0", "symbols": ["Date0$subexpression$1", (lexer.has("space") ? {type: "space"} : space), "Date0$subexpression$2"], "postprocess": g.date01},
    {"name": "Date0", "symbols": ["RelativeDay"], "postprocess": g.date00},
    {"name": "Date0", "symbols": [(lexer.has("string") ? {type: "string"} : string)], "postprocess": function ([x]){return new Date(x);}},
    {"name": "Date1", "symbols": ["Date0", (lexer.has("space") ? {type: "space"} : space), "Time"], "postprocess": g.date1},
    {"name": "Date1", "symbols": ["Date0"], "postprocess": function ([x]){return x;}},
    {"name": "Date", "symbols": ["Date1"], "postprocess": function ([x]){return {value:x};}},
    {"name": "Date$subexpression$1", "symbols": [{"literal":"after"}]},
    {"name": "Date$subexpression$1", "symbols": [{"literal":"before"}]},
    {"name": "Date", "symbols": [{"literal":"the"}, (lexer.has("space") ? {type: "space"} : space), {"literal":"day"}, (lexer.has("space") ? {type: "space"} : space), "Date$subexpression$1", (lexer.has("space") ? {type: "space"} : space), "Date1"], "postprocess": g.date}
]
  , ParserStart: "Date"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
